### ISSUE TITLE
Is this teapot or table? 

### ISSUE THREAD

**Issue by manoja328** [manoja328/VQD#1]
@karan6181 https://github.com/manoja328/VQD/blob/bb5c333aa1d5297da50d9b68b310626e8a62eb08/dataset_creation/spelling.py#L20

**Comment by karan6181** [comment]
I made this changes when I was extracting the question features. The glove embeddings didn't had this keyword and it was used only once in the VQD dataset so i thought that this label is lot similar to `table` so I have changed `teapoy` to `table`.
